version: "3.9"
  
services:
  console:
    image: nl2sqlapp
    build:
      context: .
    container_name: nl2sqlapp_console
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - model_server
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-DB}
      DATABASE_USER: ${DATABASE_USER:-USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DJANGO_SECRET_KEY: ${DJANGO_SETTINGS_MODULE}
      MODEL_SERVER_ENDPOINT: ${MODEL_SERVER_ENDPOINT:-http://model_server:11434}
      AVAILABLE_MODELS: ${AVAILABLE_MODELS:-llama2}

  circle_ci_console:
    image: nl2sqlapp
    build:
      context: .
    container_name: circle_ci_console
    depends_on:
      - db_ci
      - model_server_ci
    environment:
      DATABASE_NAME: DB
      DATABASE_USER: USER
      DATABASE_PASSWORD: PASSWORD
      DATABASE_HOST: db_ci
      DJANGO_SECRET_KEY: dummy
      MODEL_SERVER_ENDPOINT: http://model_server_ci:11434
      AVAILABLE_MODELS: llama2
      DOWNLOAD_MODELS_ON_FLY: llama2
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-PASSWORD}
      POSTGRES_USER: ${DATABASE_USER:-USER}
      POSTGRES_DB: ${DATABASE_NAME:-DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  db_ci:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-PASSWORD}
      POSTGRES_USER: ${DATABASE_USER:-USER}
      POSTGRES_DB: ${DATABASE_NAME:-DB}
    restart: on-failure

  model_server:
    image: ollama/ollama:latest
    volumes:
      - ollamadata:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  model_server_ci:
    image: ollama/ollama:latest


volumes:
  pgdata:
  ollamadata:
