# Generated by Django 5.0.3 on 2024-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeslaStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('rsi_7', models.FloatField()),
                ('rsi_14', models.FloatField()),
                ('cci_7', models.FloatField()),
                ('cci_14', models.FloatField()),
                ('sma_50', models.FloatField()),
                ('ema_50', models.FloatField()),
                ('sma_100', models.FloatField()),
                ('ema_100', models.FloatField()),
                ('macd', models.FloatField()),
                ('bollinger', models.FloatField()),
                ('TrueRange', models.FloatField()),
                ('atr_7', models.FloatField()),
                ('atr_14', models.FloatField()),
                ('next_day_close', models.FloatField()),
            ],
        ),
    ]
